"""Add workspace policies, drafts and student self-review."""
from alembic import op
import sqlalchemy as sa

revision = "0009_workspace_self_review"
down_revision = "0008_delivery_recovery"
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_publication_policy',
    sa.Column('self_review_limit', sa.Integer(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('self_review_limit >= 0', name=op.f('ck_workspace_publication_policy_limit_nonnegative')),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['course_run_homework.organization_id', 'course_run_homework.id'], name='fk_ws_policy_publication', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_publication_policy_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_publication_policy')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_publication_policy_organization_id'))
    )
    op.create_table('workspace_artifact',
    sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('digest', sa.String(length=71), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'owner_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_workspace_artifact_owner_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_artifact_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_workspace_artifact_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_artifact')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_artifact_organization_id'))
    )
    op.create_table('work_draft',
    sa.Column('publication_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('artifact_url', sa.String(length=2048), nullable=False),
    sa.Column('upload_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'publication_id'], ['course_run_homework.organization_id', 'course_run_homework.id'], name='fk_ws_draft_publication', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'student_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_work_draft_student_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'upload_id'], ['workspace_artifact.organization_id', 'workspace_artifact.id'], name='fk_ws_draft_upload', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_work_draft_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_work_draft_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_draft')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_work_draft_organization_id')),
    sa.UniqueConstraint('organization_id', 'publication_id', 'student_id', name='uq_ws_draft_scope')
    )
    op.create_table('self_review_quota',
    sa.Column('draft_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('used >= 0 AND reserved >= 0 AND reserved <= 1', name=op.f('ck_self_review_quota_valid_counters')),
    sa.ForeignKeyConstraint(['organization_id', 'draft_id'], ['work_draft.organization_id', 'work_draft.id'], name='fk_ws_quota_draft', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_self_review_quota_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_self_review_quota')),
    sa.UniqueConstraint('organization_id', 'draft_id', name='uq_ws_quota_draft'),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_self_review_quota_organization_id'))
    )
    op.create_table('self_review_run',
    sa.Column('quota_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('draft_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('homework_version_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('artifact_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('artifact_url', sa.String(length=2048), nullable=False),
    sa.Column('student_text', sa.Text(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=71), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('lease_token', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("disposition IN ('reserved','consumed','released')", name=op.f('ck_self_review_run_disposition')),
    sa.CheckConstraint("status IN ('queued','capturing','pending','running','unknown_outcome','succeeded','failed')", name=op.f('ck_self_review_run_status')),
    sa.ForeignKeyConstraint(['organization_id', 'artifact_id'], ['workspace_artifact.organization_id', 'workspace_artifact.id'], name='fk_ws_run_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'draft_id'], ['work_draft.organization_id', 'work_draft.id'], name='fk_ws_run_draft', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'homework_version_id'], ['homework_version.organization_id', 'homework_version.id'], name='fk_ws_run_homework', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'quota_id'], ['self_review_quota.organization_id', 'self_review_quota.id'], name='fk_ws_run_quota', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_self_review_run_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_self_review_run')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_self_review_run_organization_id'))
    )
    op.create_table('self_review_event_receipt',
    sa.Column('run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('digest', sa.String(length=71), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'run_id'], ['self_review_run.organization_id', 'self_review_run.id'], name='fk_ws_event_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_self_review_event_receipt_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_self_review_event_receipt')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_self_review_event_receipt_organization_id'))
    )
    op.create_table('self_review_quota_event',
    sa.Column('run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.CheckConstraint("action IN ('reserve','consume','release')", name=op.f('ck_self_review_quota_event_action')),
    sa.ForeignKeyConstraint(['organization_id', 'run_id'], ['self_review_run.organization_id', 'self_review_run.id'], name='fk_ws_qevent_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_self_review_quota_event_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_self_review_quota_event')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_self_review_quota_event_organization_id')),
    sa.UniqueConstraint('organization_id', 'run_id', 'action', name='uq_ws_quota_event')
    )
    op.create_table('workspace_preferences',
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_workspace_preferences_user_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_preferences_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_workspace_preferences_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_preferences')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_preferences_organization_id')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_ws_preferences_user')
    )
    op.create_table('student_reviewer_assignment',
    sa.Column('course_run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'course_run_id'], ['course_run.organization_id', 'course_run.id'], name='fk_ws_assignment_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'reviewer_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_student_reviewer_assignment_reviewer_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'student_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_student_reviewer_assignment_student_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_student_reviewer_assignment_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('fk_student_reviewer_assignment_reviewer_id_user')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_student_reviewer_assignment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_reviewer_assignment')),
    sa.UniqueConstraint('organization_id', 'course_run_id', 'student_id', name='uq_ws_assignment_student'),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_student_reviewer_assignment_organization_id'))
    )
    op.create_table('homework_private_details',
    sa.Column('reviewer_guidance', sa.Text(), nullable=False),
    sa.Column('reference_upload_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('criterion_classes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['homework_version.organization_id', 'homework_version.id'], name='fk_ws_private_homework', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'reference_upload_id'], ['workspace_artifact.organization_id', 'workspace_artifact.id'], name='fk_ws_private_reference', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_homework_private_details_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework_private_details')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_homework_private_details_organization_id'))
    )
    op.create_table('workspace_review_outcome',
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('revision_deadline', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['review_iteration.organization_id', 'review_iteration.id'], name='fk_ws_outcome_iteration', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_review_outcome_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_review_outcome')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_review_outcome_organization_id'))
    )
    op.create_table('workspace_export',
    sa.Column('course_run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('error', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'artifact_id'], ['workspace_artifact.organization_id', 'workspace_artifact.id'], name='fk_ws_export_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'course_run_id'], ['course_run.organization_id', 'course_run.id'], name='fk_ws_export_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'owner_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_workspace_export_owner_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_export_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_workspace_export_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_export')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_export_organization_id'))
    )
    op.create_table('workspace_notification',
    sa.Column('course_run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('recipient_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'course_run_id'], ['course_run.organization_id', 'course_run.id'], name='fk_ws_note_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'recipient_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_workspace_notification_recipient_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_notification_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_workspace_notification_recipient_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_notification')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_notification_organization_id'))
    )
    op.create_table('workspace_course_details',
    sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['course.organization_id', 'course.id'], name='fk_ws_course_details', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'owner_id'], ['organization_membership.organization_id', 'organization_membership.user_id'], name='fk_workspace_course_details_owner_id_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_course_details_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_course_details')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_course_details_organization_id'))
    )
    op.create_table('workspace_run_settings',
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("priority IN ('assigned','deadline')", name=op.f('ck_workspace_run_settings_priority')),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['course_run.organization_id', 'course_run.id'], name='fk_ws_run_settings', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_run_settings_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_run_settings')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_run_settings_organization_id'))
    )
    op.create_table('homework_editor_draft',
    sa.Column('homework_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('course_run_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'course_run_id'], ['course_run.organization_id', 'course_run.id'], name='fk_ws_editor_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'homework_id'], ['homework.organization_id', 'homework.id'], name='fk_ws_editor_homework', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_homework_editor_draft_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework_editor_draft')),
    sa.UniqueConstraint('organization_id', 'homework_id', 'course_run_id', name='uq_ws_editor_scope'),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_homework_editor_draft_organization_id'))
    )
    op.create_table('submission_policy_snapshot',
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('policy_revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['submission_version.organization_id', 'submission_version.id'], name='fk_ws_submission_policy', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_submission_policy_snapshot_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_policy_snapshot')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_submission_policy_snapshot_organization_id'))
    )
    op.create_table('workspace_published_grade',
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'id'], ['review_publication.organization_id', 'review_publication.id'], name='fk_ws_published_grade', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workspace_published_grade_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_published_grade')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_workspace_published_grade_organization_id'))
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table("workspace_published_grade")
    op.drop_table("submission_policy_snapshot")
    op.drop_table("homework_editor_draft")
    op.drop_table("workspace_run_settings")
    op.drop_table("workspace_course_details")
    op.drop_table("workspace_notification")
    op.drop_table("workspace_export")
    op.drop_table("workspace_review_outcome")
    op.drop_table("homework_private_details")
    op.drop_table("student_reviewer_assignment")
    op.drop_table("workspace_preferences")
    op.drop_table("self_review_quota_event")
    op.drop_table("self_review_event_receipt")
    op.drop_table("self_review_run")
    op.drop_table("self_review_quota")
    op.drop_table("work_draft")
    op.drop_table("workspace_artifact")
    op.drop_table("workspace_publication_policy")
